Repository AY2021S1-CS2113T-F12-1/tp, pull requests merged in 2020-11, with the labels that each got.

#222 Improve parser error handling and update user guide
  docs/UserGuide.md
  docs/images/PlanNUSBackground.jpg
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
Labels: feature.AcademicPlanner, type.BugFix

#229 Update set target function to show clearer error messages, add help function in capcalc
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetTargetUtilsTest.java
  text-ui-test/EXPECTED.TXT
Labels: feature.CAPCalculator, type.BugFix

#230 Update Documentation
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/team/Lam.md
Labels: type.Documentation

#231 Tweak the Ui of set su commands as of PE dry run
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetSuUtilsTest.java
Labels: feature.CAPCalculator, type.BugFix

#233 Update PPP
  .gitignore
  docs/team/Lam.md
Labels: type.Documentation

#234 Rename PPP
  docs/AboutUs.md
  docs/team/jerroldlam.md
Labels: type.Documentation

#235 Change the error messages for removeModuleCommand
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
Labels: feature.AcademicPlanner, type.BugFix

#236 [DG] Added use cases for acadplanner commands
  docs/DeveloperGuide.md
Labels: feature.AcademicPlanner, type.Documentation

#237 Added functionality to allow swapping between apps, Shorten app commands
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/global/App.java
  src/main/java/seedu/duke/global/Command.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: feature.All, type.Enhancement

#238 Updated help command for both apps, changed parsing to uppercase in capcalc app and main menu
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/parser/AppParser.java
Labels: code.Quality, feature.All, type.Bug

#239 Update documentation
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/base/addModuleCommand_sequence.drawio
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
  docs/team/harryleecp.md
  docs/team/juzihao.md
  docs/team/vanessa-kang.md
Labels: type.Documentation

#241 [UG] General cleanup and improvements.
  docs/UserGuide.md
  docs/images/UserGuide/acadplan_capcalcswitch.png
  docs/images/UserGuide/acadplan_features.png
  docs/images/UserGuide/acadplan_help.png
  docs/images/UserGuide/capcalc_acadplanswitch.png
  docs/images/UserGuide/capcalc_features.png
  docs/images/UserGuide/capcalc_help.png
  docs/team/vanessa-kang.md
Labels: type.Documentation

#242 [UG, DG] Readability improvements
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#243 Update UG after PE dry run
  docs/UserGuide.md
  docs/images/UserGuide/Main_Page_Features.png
  docs/images/UserGuide/capcalc_current.png
  docs/images/UserGuide/capcalc_set_su_modules_output.png
  docs/images/UserGuide/capcalc_set_su_modules_output1.png
  docs/images/UserGuide/capcalc_set_su_modules_output2.png
  docs/images/UserGuide/capcalc_set_su_modules_output3.png
  docs/images/UserGuide/capcalc_set_su_semester_output.png
  docs/images/UserGuide/capcalc_set_su_semester_output1.png
  docs/images/UserGuide/capcalc_set_su_semester_output2.png
  docs/images/UserGuide/capcalc_set_su_semester_output3.png
  docs/team/juzihao.md
Labels: type.Documentation

#244 Update PPP
  docs/team/juzihao.md
Labels: feature.All, type.Documentation

#245 [DG] Added instructions for manual testing.
  docs/DeveloperGuide.md
Labels: type.Documentation

#246 Refactor code and update documentation
  docs/UserGuide.md
  docs/team/jerroldlam.md
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/SearchModulesCommand.java
  src/main/java/seedu/duke/global/LoggingTool.java
Labels: code.Quality, type.Documentation

#247 Update PPP
  docs/team/juzihao.md
Labels: type.Documentation

#248 Add Profile picture for Jerrold
  docs/AboutUs.md
  docs/images/Profile/Jerrold.JPG
Labels: type.Documentation

#250 Implemented storage class after every end of add, edit or remove command
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/SearchModulesCommand.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/test/java/seedu/duke/apps/academicplanner/AcademicPlannerParserTest.java
  src/test/java/seedu/duke/parser/AppParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: feature.Storage, type.Enhancement

#252 Added PPP
  docs/team/khenus.md
Labels: type.Enhancement

#253 Support retaking of failed modules
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
Labels: feature.AcademicPlanner, type.BugFix

#255 Fix whitespace error for academic planner parser parameters
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
Labels: feature.AcademicPlanner, type.BugFix

#256 Show unique message for acadplan parser
  docs/team/jerroldlam.md
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
Labels: feature.AcademicPlanner

#257 Fix whitespace being read as parameter and update documents
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
Labels: feature.AcademicPlanner, type.BugFix, type.Documentation

#258 Added support for duplicated modules operatation
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
  src/main/java/seedu/duke/global/objects/Person.java
  src/test/java/seedu/duke/apps/academicplanner/commons/EditUtilsTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/RemoveUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: feature.AcademicPlanner, type.Enhancement

#259 Update user guide
  .gitignore
  docs/UserGuide.md
  docs/team/jerroldlam.md
Labels: type.Documentation

#260 Refactor AddModuleCommand and AddUtils
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
Labels: code.Quality, feature.AcademicPlanner

#261 Added stricter checks for retaking modules
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
  src/test/java/seedu/duke/apps/academicplanner/commons/SharedUtilsTest.java
Labels: feature.AcademicPlanner, type.Test

#262 Refactor AddModuleCommand
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
Labels: code.Quality, feature.AcademicPlanner

#263 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#264 Added more exceptions to Cap Calculator Parser
  docs/team/juzihao.md
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuByModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
Labels: code.Quality, feature.CAPCalculator, type.Test

#265 Update AddModuleCommand in DG and add more parser test
  docs/DeveloperGuide.md
  docs/base/addModuleCommand_sequence.drawio
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/test/java/seedu/duke/apps/academicplanner/AcademicPlannerParserTest.java
Labels: feature.AcademicPlanner, type.Documentation, type.Test

#270 Minor bug fixes
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/test/java/seedu/duke/apps/academicplanner/commons/RemoveUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: type.BugFix

#272 Added parser diagram for DG
  docs/DeveloperGuide.md
  docs/base/Parser_architecture.drawio
  docs/images/DeveloperGuide/Parser_architecture.png
Labels: type.Documentation

#273 Update DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#274 Added further checks for edition and addition of modules
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
  src/main/java/seedu/duke/storage/commons/SaveUtils.java
  src/test/java/seedu/duke/apps/academicplanner/commons/EditUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: type.BugFix

#275 Refactor EditUtils and SharedUtils code
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
Labels: code.Quality

#276 Add authorship for documentation
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/DocumentationGuide.md
  docs/LoggingGuide.md
  docs/TestingGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#278 Add authorship for DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#280 Added checks for module grade validity for save loading
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
  src/main/java/seedu/duke/storage/commons/FieldValidator.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
  src/test/java/seedu/duke/storage/commons/FieldValidatorTest.java
Labels: feature.Storage, type.Enhancement

#279 Fix bug of being able to retake a module while there is a grade of S or CS
  .gitignore
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/global/objects/PartialModule.java
Labels: feature.AcademicPlanner, type.BugFix

#282 Minor bug fixes
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/global/objects/PartialModule.java
Labels: type.BugFix

#283 Suport logging to different folder
  .gitignore
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/moduleloader/ModuleLoader.java
  src/main/java/seedu/duke/global/objects/PartialModule.java
  text-ui-test/EXPECTED.TXT
Labels: feature.All, type.Enhancement

#284 Update DG images
  docs/base/Ui architecture.drawio
  docs/base/addModuleCommand_state2.drawio
  docs/images/DeveloperGuide/Ui_architecture.png
  docs/images/DeveloperGuide/addModuleCommand_state2.png
Labels: type.Documentation

#287 Amended final flow for edit command
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Profile/Harry.jpg
  docs/images/UserGuide/edit_module_grade.png
  docs/images/UserGuide/edit_module_semester.png
Labels: type.Documentation

#289 [DG] updated manual testing instructions
  docs/DeveloperGuide.md
Labels: type.Documentation

#288 Update grammar error for current command
  docs/base/Parser_architecture.drawio
  docs/images/DeveloperGuide/Parser_architecture.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_sequence.png
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#290 Update DG
  docs/DeveloperGuide.md
  docs/base/Ui_architecture_1.drawio
  docs/base/addModuleCommand_activity.drawio
  docs/base/addModuleCommand_finalState.drawio
  docs/base/addModuleCommand_state2.drawio
  docs/base/addModuleCommand_state6.drawio
  docs/images/DeveloperGuide/Ui_architecture.png
  docs/images/DeveloperGuide/addModuleCommand_activity.png
  docs/images/DeveloperGuide/addModuleCommand_finalState.png
  docs/images/DeveloperGuide/addModuleCommand_state2.png
  docs/images/DeveloperGuide/addModuleCommand_state6.png
Labels: type.Documentation

#291 Added checks for module credit tempering
  docs/base/Packages Interaction.drawio
  docs/images/DeveloperGuide/Packages_Interaction.png
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/storage/commons/FieldValidator.java
Labels: feature.Storage, type.BugFix

#292 add explanation for XYZ notation in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#293 Amended wrong diagrams in the DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Storage_architecture.png
  docs/images/DeveloperGuide/editModuleCommand_sequence.png
  docs/images/DeveloperGuide/removeModuleCommand_sequence.png
Labels: type.Documentation

#294 Amended activity diagrams for edit and remove commands
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/editModuleCommand_activity.png
  docs/images/DeveloperGuide/removeModuleCommand_activity.png
Labels: type.Documentation

#295 Update PPP
  docs/team/jerroldlam.md
Labels: type.Documentation

#296 Update DG
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/currentCommand_sequence.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_sequence.png
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
Labels: type.Documentation

#297 Update PPP and About Us
  docs/AboutUs.md
  docs/images/Profile/Zihao.jpg
  docs/team/juzihao.md
Labels: type.Documentation

#298 Added return control for module details sequence diagram
  docs/images/DeveloperGuide/moduleDetailsCommand_sequence.png
Labels: type.Documentation

#299 Update shfting error messages
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
Labels: feature.AcademicPlanner

#300 Updated PPP + AboutUs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/Profile/Vanessa.jpg
  docs/team/vanessa-kang.md
Labels: type.Documentation

#301 Update current command sequence diagram
  docs/images/DeveloperGuide/currentCommand_sequence.png
Labels: type.Documentation

#302 Update features coming soon
  README.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: type.Documentation

#303 Updated DG Diagram and PPP
  AddModuleCommand.log
  ModuleLoader.log
  docs/base/Parser_architecture.drawio
  docs/images/DeveloperGuide/Parser_architecture.png
  docs/team/khenus.md
Labels: type.Documentation

#304 Added image for PPP
  docs/AboutUs.md
  docs/images/Profile/khenus.jpg
Labels: type.Documentation

#305 [UG] added ToC hyperlinks + some language improvements
  docs/UserGuide.md
Labels: type.Documentation

#308 Update draw io files and sequence diagram
  docs/base/currentCommand_sequence.drawio
  docs/base/setSuBySemesterCommand_finalState.drawio
  docs/base/setSuBySemesterCommand_sequence.drawio
  docs/base/setSu_Command_5state.drawio
  docs/base/setSu_command_Initial.drawio
  docs/images/DeveloperGuide/currentCommand_sequence.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_sequence.png
Labels: type.Documentation

#310 Fix not being able to shift bug
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
Labels: type.BugFix

#312 [UG+DG] Further refinements
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/moduleDetailsCommand_sequence.png
Labels: type.Documentation

#313 update PPP + upload draw.io file
  docs/base/moduleDetailsCommand.xml
  docs/team/vanessa-kang.md
Labels: type.Documentation

#314 Fix bugs when shifting modules
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
Labels: type.BugFix

#315 Update PPP and AboutUs
  docs/AboutUs.md
  docs/team/jerroldlam.md
Labels: type.Documentation

#316 Fixed Bug in storage check
  src/main/java/seedu/duke/storage/commons/FieldValidator.java
Labels: feature.Storage, type.BugFix

#317 Fix handling of duplicated modules
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
Labels: type.BugFix

#318 Added further checks for adding modules
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/SharedUtils.java
Labels: feature.AcademicPlanner, type.BugFix

#319 Add cautions in UG
  docs/UserGuide.md
Labels: type.Documentation

#320 Fix Capcalc message
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
Labels: type.BugFix

#321 [PPP] fixed broken reposense link
  docs/team/vanessa-kang.md
Labels: type.BugFix, type.Documentation

#322 Updated PPP
  docs/team/khenus.md
Labels: type.Documentation
