Repository AY2021S1-CS2113T-F12-1/tp, pull requests merged in 2020-10, with the labels that each got.

#13 V0.3 Added Capcalc functions
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/apps/CapCalculator.java
Labels: feature.GetCAP, severity.Low

#29 Add prompts for user when any invalid command is entered in Academic Planner
  src/main/java/seedu/duke/PlanNUS.java
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/apps/CapCalculator.java
  src/main/java/seedu/duke/moduledata/ModuleDatum.java
  src/main/java/seedu/duke/moduledata/ModuleInitializer.java
  src/main/java/seedu/duke/objects/Module.java
  src/main/java/seedu/duke/objects/Person.java
  src/test/java/seedu/duke/PlanNUSTest.java
Labels: code.Quality, code.Standard

#33 V0.2 Updated file structure for gradle checks, updated expected test output
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/moduledata/ModuleDatum.java
  src/main/java/seedu/duke/moduledata/ModuleInitializer.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: feature.All, feature.ModuleLoader, type.BugFix, type.Enhancement

#34 V0.3 Refactored Update CAP function
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/exceptions/AcademicException.java
Labels: code.Standard, feature.AcademicPlanner

#36 Refactor and clean up Academic Planner code
  docs/AboutUs.md
  docs/team/Harry.md
  docs/team/Khenus.md
  docs/team/Lam.md
  docs/team/Vanessa.md
  docs/team/Zihao.md
  docs/team/johndoe.md
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/AcademicPlanner.java
Labels: feature.AcademicPlanner, type.Enhancement

#37 Add user guide for add module function
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/apps/AcademicPlanner.java
Labels: feature.AcademicPlanner, type.Documentation, type.Enhancement

#42 V0.5 Added Parser and Ui for centralised scanner
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/apps/App.java
  src/main/java/seedu/duke/apps/CapCalculator.java
  src/main/java/seedu/duke/apps/ModuleInitializer.java
  src/main/java/seedu/duke/exceptions/AppParserException.java
  src/main/java/seedu/duke/objects/FullModule.java
  src/main/java/seedu/duke/objects/PartialModule.java
  src/main/java/seedu/duke/objects/Person.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/Duke.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
Labels: feature.All, type.Addition

#43 Refactor Academic planner and fix exception bug
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/apps/CapCalculator.java
  src/main/java/seedu/duke/parser/AppParser.java
  text-ui-test/EXPECTED.TXT
Labels: feature.AcademicPlanner, type.BugFix, type.Enhancement

#49 Update Readme.md with weblinks
  docs/README.md
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/commands/AcademicPlannerAddCommand.java
  src/main/java/seedu/duke/commands/AcademicPlannerCommand.java
  src/main/java/seedu/duke/commons/AcademicPlannerCommon.java
  src/main/java/seedu/duke/exceptions/AcademicPlannerParserException.java
  src/main/java/seedu/duke/parser/AcademicPlannerParser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation, type.Enhancement

#53 V0.6 Updated Academic Planner with different command and parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/AcademicPlanner.java
  src/main/java/seedu/duke/apps/CapCalculator.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/commands/AcademicPlannerAddCommand.java
  src/main/java/seedu/duke/commands/AcademicPlannerCommand.java
  src/main/java/seedu/duke/exceptions/CommandParserException.java
  src/main/java/seedu/duke/globalcommons/App.java
  src/main/java/seedu/duke/globalcommons/Command.java
  src/main/java/seedu/duke/parser/AcademicPlannerParser.java
  src/main/java/seedu/duke/parser/AppParser.java
  text-ui-test/EXPECTED.TXT
Labels: code.Quality, feature.AcademicPlanner, type.Enhancement

#54 Add JUnit test for addModuleToUserFunction
  src/test/java/seedu/duke/apps/academicplanner/commons/AddUtilsTest.java
Labels: feature.AcademicPlanner, type.Test

#58 Refactor functions for Cap Calculator and more OOP
  src/main/java/seedu/duke/apps/CapCalculator.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculator.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/main/java/seedu/duke/parser/AppParser.java
  text-ui-test/EXPECTED.TXT
Labels: code.Quality, feature.CAPCalculator

#61 Added some JUnit test for Cap Calculator parser.
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorParserTest.java
Labels: type.Test

#59 Fix bug where exit from PlanNUS main menu will trigger help messages
  src/main/java/seedu/duke/Duke.java
  text-ui-test/EXPECTED.TXT
Labels: type.BugFix

#62 Update javadoc comments
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/ModuleInitializer.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/globalcommons/App.java
  src/main/java/seedu/duke/globalcommons/Command.java
  src/main/java/seedu/duke/objects/PartialModule.java
  src/main/java/seedu/duke/objects/Person.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Documentation, type.Enhancement

#64 Fix link to releases for user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Documentation, type.Enhancement

#65 Clean up code and update addModuleToUser test
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculator.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/main/java/seedu/duke/exceptions/AcademicException.java
  src/main/java/seedu/duke/exceptions/AcademicPlannerParserException.java
  src/main/java/seedu/duke/exceptions/AppParserException.java
  src/main/java/seedu/duke/exceptions/CapCalculatorException.java
  src/main/java/seedu/duke/exceptions/CommandParserException.java
  src/main/java/seedu/duke/objects/PartialModule.java
  src/main/java/seedu/duke/objects/Person.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AddUtilsTest.java
Labels: code.Quality, code.Standard, type.Addition, type.Documentation, type.Enhancement

#66 V0.7 Added test for Module initializer
  build.gradle
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/apps/ModuleInitializer.java
  src/test/java/seedu/duke/apps/ModuleInitializerTest.java
  text-ui-test/runtest.bat
Labels: feature.ModuleLoader, type.Test

#67 Add assertions and logging for add module functions in academic planner
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
Labels: type.Addition

#68 Added a basic structure for DG, more information to be added
  docs/DeveloperGuide.md
Labels: feature.All, type.Documentation

#70 Added exception for module loader
  build.gradle
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/ModuleInitializer.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/exceptions/AcademicException.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/CapCalculatorException.java
  src/main/java/seedu/duke/apps/moduleloader/ModuleLoader.java
  src/main/java/seedu/duke/apps/moduleloader/exceptions/ModuleLoaderException.java
  src/main/java/seedu/duke/exceptions/AcademicPlannerParserException.java
  src/main/java/seedu/duke/exceptions/InvalidCapException.java
  src/main/java/seedu/duke/exceptions/InvalidCreditException.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/test/java/seedu/duke/PlanNus.java
  src/test/java/seedu/duke/apps/ModuleLoaderTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AddUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
Labels: feature.ModuleLoader, type.Enhancement

#72 Fix bug where adding additional spaces behind inputs in academic planner throws exception
  docs/AboutUs.md
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
Labels: feature.AcademicPlanner, type.BugFix

#73 Add JUnit tests for EditUtil and RemoveUtil
  src/test/java/seedu/duke/apps/academicplanner/commons/EditUtilsTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/RemoveUtilsTest.java
Labels: type.Enhancement, type.Test

#77 [V1.0] Added print academic calendar feature
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
Labels: feature.PrintCalander, type.Addition

#78 Edit JavaDoc comments for print command
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
Labels: type.Documentation

#85 V1.1 Updated algorithm for module access
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/objects/Person.java
Labels: feature.AcademicPlanner, type.Enhancement

#88 Update user guide to add help command and view full or view by semester for ACAD PLAN
  docs/UserGuide.md
  docs/images/acadplan_help.PNG
  docs/images/acadplan_viewfull.PNG
  docs/images/acadplan_viewmain.PNG
  docs/images/acadplan_viewsem.PNG
Labels: type.Addition, type.Documentation

#91 Update user guide
  docs/UserGuide.md
  src/main/java/seedu/duke/PlanNus.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#96 Add message to show number of total mcs taken in the current command in capcalc
  .gitignore
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  src/main/java/seedu/duke/apps/moduleloader/exceptions/ModuleLoaderException.java
  text-ui-test/EXPECTED.TXT
Labels: type.Addition

#97 Support logging of different functions to seperate textfiles
  .gitignore
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/moduleloader/ModuleLoader.java
  src/main/java/seedu/duke/globalcommons/LoggingTool.java
  text-ui-test/EXPECTED.TXT
Labels: feature.All, type.Addition

#98 Refactored storage and bug fixes
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/InvalidCapException.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/InvalidCreditException.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/commons/FieldValidator.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
  src/main/java/seedu/duke/storage/commons/SaveUtils.java
  src/main/java/seedu/duke/storage/exceptions/CorruptedSaveFileException.java
  src/main/java/seedu/duke/storage/exceptions/LoadFileException.java
  src/main/java/seedu/duke/storage/exceptions/SaveFileException.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: feature.Storage, type.Enhancement

#99 Supports set su algorithms inside Cap Calculator.
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/SetSuParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuByModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuBySemesterCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  text-ui-test/EXPECTED.TXT
Labels: feature.CAPCalculator, type.Addition

#100 Refactor and test current command in capcalc
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: feature.CAPCalculator, type.Test

#101 Refactor Academic Planner
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorter.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/apps/academicplanner/exceptions/AcademicException.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
  text-ui-test/EXPECTED.TXT
Labels: code.Quality, code.Standard, feature.AcademicPlanner

#103 Fix bug where header still prints if no modules exist for the semeseter in view by semester
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
Labels: feature.AcademicPlanner, type.BugFix

#105 Update Developer guide
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Architecture.png
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintCalenderCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorter.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/SetSuParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/CurrentCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuByModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuBySemesterCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/main/java/seedu/duke/apps/moduleloader/ModuleLoader.java
  src/main/java/seedu/duke/global/App.java
  src/main/java/seedu/duke/global/Command.java
  src/main/java/seedu/duke/global/LoggingTool.java
  src/main/java/seedu/duke/global/exceptions/AppParserException.java
  src/main/java/seedu/duke/global/exceptions/CommandParserException.java
  src/main/java/seedu/duke/global/objects/FullModule.java
  src/main/java/seedu/duke/global/objects/PartialModule.java
  src/main/java/seedu/duke/global/objects/Person.java
  src/main/java/seedu/duke/parser/AppParser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
  src/main/java/seedu/duke/storage/commons/SaveUtils.java
  src/test/java/seedu/duke/apps/ModuleLoaderTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AddUtilsTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/EditUtilsTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/RemoveUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: feature.All, type.Documentation

#108 Add tests for calendar sorter and current cap command
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorter.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorterTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
Labels: type.Test

#111 Fix bug where add remove or edit command with no parameters return wrong error message
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
Labels: type.BugFix

#112 WIP Finished Sequence Diagram for PlanNUS
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Architecture.png
  docs/images/DeveloperGuide/Packages Interaction.png
  docs/images/DeveloperGuide/Project structure.png
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: feature.All, type.Documentation

#113 WIP Finished Sequence diagram for PlanNUS
  docs/DeveloperGuide.md
Labels: feature.All, type.Documentation

#114 Add Developer Guide for add module command
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Packages_Interaction.png
  docs/images/DeveloperGuide/Project_structure.png
Labels: type.Documentation

#104 Added view module details feature (v2.0, as per #23)
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/ModuleDetailsCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: feature.AcademicPlanner, type.Addition

#115 Fix references
  src/main/java/seedu/duke/apps/academicplanner/commands/ModuleDetailsCommand.java
Labels: type.BugFix

#116 Update Developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#117 V1.3 Fixed bug for removing module from array list
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
Labels: feature.AcademicPlanner, type.BugFix

#122 Update developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
Labels: type.Documentation

#124 V1.4 Fixed assertion error
  build.gradle
  docs/images/DeveloperGuide/PackagesInteraction.png
  docs/images/DeveloperGuide/ProjectStructure.png
  src/main/java/seedu/duke/PlanNus.java
Labels: feature.All, type.BugFix

#125 Add sequence diagram for AddModuleCommand
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
Labels: type.Documentation

#126 Add diagrams for developer guide
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/addModuleCommand_activity .png
  docs/images/DeveloperGuide/addModuleCommand_finalState.png
  docs/images/DeveloperGuide/addModuleCommand_initialState.png
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
  docs/images/DeveloperGuide/addModuleCommand_state2.png
  docs/images/DeveloperGuide/addModuleCommand_state6.png
Labels: type.Documentation

#127 Fix wrong file name in images
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/addModuleCommand_activity.png
Labels: type.Documentation

#128 Update documentation
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/addModuleCommand_finalState.png
Labels: type.Documentation

#129 Bug fix on Cap Calculator
  src/main/java/seedu/duke/apps/capcalculator/commons/CalculatorUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
Labels: feature.CAPCalculator, type.BugFix

#130 Update DG with logger information
  docs/DeveloperGuide.md
  docs/README.md
Labels: type.Documentation

#131 Readd search modules function (#24) that accidentally got deleted during merge conflict resolution
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/SearchModulesCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: feature.AcademicPlanner, type.Addition

#133 Added JUnit for set su ultils
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuBySemesterCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetTargetCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetSuUtilsTest.java
Labels: type.Documentation

#134 Fix broken link in UG and update README
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: type.Documentation

#136 Update documentation
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: type.Documentation

#135 Add implementation info for remove and edit modules command in DG
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/editModuleCommand_activity.png
  docs/images/DeveloperGuide/editModuleCommand_finalState.png
  docs/images/DeveloperGuide/editModuleCommand_initialState.png
  docs/images/DeveloperGuide/editModuleCommand_sequence.png
  docs/images/DeveloperGuide/removeModuleCommand_activity.png
  docs/images/DeveloperGuide/removeModuleCommand_finalState.png
  docs/images/DeveloperGuide/removeModuleCommand_initialState.png
  docs/images/DeveloperGuide/removeModuleCommand_sequence.png
Labels: type.Documentation

#138 V1.4 Updated UI for ease of use
  src/main/java/seedu/duke/PlanNus.java
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorApp.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/CapCalculatorException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetSuUtilsTest.java
  src/test/java/seedu/duke/apps/moduleloader/ModuleLoaderTest.java
  text-ui-test/EXPECTED.TXT
Labels: feature.All, type.Enhancement

#139 Update DG for set su command
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/setSuBySemesterCommand_State5.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_activity.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_finalState.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_initialState.png
  docs/images/DeveloperGuide/setSuBySemesterCommand_sequence.png
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
Labels: feature.CAPCalculator, type.Documentation

#140 Center all UG Images
  docs/UserGuide.md
Labels: type.Documentation

#141 V1.5 updated DG, UG and LG
  docs/DeveloperGuide.md
  docs/LoggingGuide.md
  docs/UserGuide.md
  docs/images/DeveloperGuide/editModuleCommand_activity.png
  docs/images/Main_Page_Features.png
  docs/images/UserGuide/Main_Page_Features.PNG
  docs/images/UserGuide/acadplan_details.png
  docs/images/UserGuide/acadplan_features.PNG
  docs/images/UserGuide/acadplan_help.png
  docs/images/UserGuide/acadplan_search_full.png
  docs/images/UserGuide/acadplan_search_part.png
  docs/images/UserGuide/acadplan_viewfull.png
  docs/images/UserGuide/acadplan_viewsem.png
  docs/images/UserGuide/add_module.png
  docs/images/UserGuide/capcalc_current.png
  docs/images/UserGuide/capcalc_features.png
  docs/images/UserGuide/capcalc_set_su_module.png
  docs/images/UserGuide/capcalc_set_su_modules_output.png
  docs/images/UserGuide/capcalc_set_su_semester.png
  docs/images/UserGuide/capcalc_set_su_semester_output.png
  docs/images/UserGuide/capcalc_set_target.png
  docs/images/UserGuide/edit_module.png
  docs/images/UserGuide/edit_module_grade.png
  docs/images/UserGuide/edit_module_semester.png
  docs/images/UserGuide/exit_PlanNUS.png
  docs/images/UserGuide/exit_acadplan.png
  docs/images/UserGuide/exit_capcalc.png
  docs/images/UserGuide/file_is_empty.png
  docs/images/UserGuide/file_not_found.png
  docs/images/UserGuide/module_loaded.png
  docs/images/UserGuide/remove_module.png
  docs/images/acadplan_details.png
  docs/images/acadplan_features.png
  docs/images/acadplan_help.PNG
  docs/images/acadplan_search_full.png
  docs/images/acadplan_search_part.png
  docs/images/acadplan_viewfull.PNG
  docs/images/acadplan_viewmain.PNG
  docs/images/acadplan_viewsem.PNG
  docs/images/add_module.png
  docs/images/capcalc_current.png
  docs/images/capcalc_features.png
  docs/images/capcalc_set_su_module.png
  docs/images/capcalc_set_su_modules.png
  docs/images/capcalc_set_su_modules_output.png
  docs/images/capcalc_set_su_modules_prompt.png
  docs/images/capcalc_set_su_semester.png
  docs/images/capcalc_set_su_semester_output.png
  docs/images/capcalc_set_target.png
  docs/images/edit_module.png
  docs/images/edit_module_grade.png
  docs/images/edit_module_semester.png
  docs/images/exit_PlanNUS.png
  docs/images/exit_acadplan.png
  docs/images/exit_capcalc.png
  docs/images/file_not_found.png
  docs/images/module_loaded.png
  docs/images/remove_module.png
Labels: feature.All, type.Documentation

#142 V1.5 updated DG, UG and LG
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
Labels: feature.All, type.Documentation

#143 V1.5 updated DG, UG and LG
  docs/DeveloperGuide.md
  docs/images/UserGuide/Main_Page_Features.png
  docs/images/UserGuide/acadplan_features.png
Labels: feature.All, type.Documentation

#145 V1.5 Updated UG, DG and LG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: feature.All, type.Documentation

#146 Update DG
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Documentation

#147 Fix DG diagrams
  docs/images/DeveloperGuide/Packages_Interaction.png
  docs/images/DeveloperGuide/addModuleCommand_sequence.png
Labels: type.Documentation

#150 Amend sequence diagrams for remove and edit in DG
  docs/images/DeveloperGuide/editModuleCommand_sequence.png
  docs/images/DeveloperGuide/removeModuleCommand_sequence.png
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/RemoveModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/EditUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/RemoveUtils.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/commons/LoadUtils.java
  src/main/java/seedu/duke/storage/commons/SaveUtils.java
  src/main/java/seedu/duke/storage/exceptions/LoadFileException.java
  src/main/java/seedu/duke/storage/exceptions/SaveFileException.java
Labels: type.Documentation

#149 Add authorship and parser tests
  .gitignore
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commands/PrintHelpCommand.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorter.java
  src/main/java/seedu/duke/apps/academicplanner/commons/AddUtils.java
  src/main/java/seedu/duke/apps/academicplanner/commons/ModuleValidator.java
  src/main/java/seedu/duke/apps/academicplanner/commons/PrintUtils.java
  src/main/java/seedu/duke/global/LoggingTool.java
  src/main/java/seedu/duke/global/objects/PartialModule.java
  src/main/java/seedu/duke/global/objects/Person.java
  src/test/java/seedu/duke/apps/academicplanner/AcademicPlannerParserTest.java
  src/test/java/seedu/duke/parser/AppParserTest.java
Labels: type.Test

#151 Added testing for Set Su Parser
  .gitignore
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/SetSuParser.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/test/java/seedu/duke/apps/capcalculator/CapCalculatorAppParserTest.java
  src/test/java/seedu/duke/apps/capcalculator/SetSuParserTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetSuUtilsTest.java
Labels: type.Test

#152 Update user guide
  docs/UserGuide.md
Labels: type.Documentation

#154 Update user guide, add authorship for tests and add testing guide for DG
  docs/DeveloperGuide.md
  docs/LoggingGuide.md
  docs/README.md
  docs/TestingGuide.md
  docs/UserGuide.md
  src/test/java/seedu/duke/apps/academicplanner/AcademicPlannerParserTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AcademicCalendarSorterTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/AddUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commands/CurrentCommandTest.java
  src/test/java/seedu/duke/parser/AppParserTest.java
Labels: type.Documentation, type.Test

#156 Added authorship for functional codes and tests
  src/test/java/seedu/duke/apps/academicplanner/commons/EditUtilsTest.java
  src/test/java/seedu/duke/apps/academicplanner/commons/RemoveUtilsTest.java
Labels: feature.All

#155 Update DG
  docs/Configuration.md
  docs/DeveloperGuide.md
Labels: feature.All, type.Documentation

#158 Update links in DG guides
  README.md
  docs/Configuration.md
  docs/LoggingGuide.md
  docs/README.md
  docs/TestingGuide.md
Labels: type.Documentation

#159 Updated pictures for UG
  docs/UserGuide.md
  docs/images/UserGuide/Main_Page_Features.png
  docs/images/UserGuide/acadplan_details.png
  docs/images/UserGuide/acadplan_features.png
  docs/images/UserGuide/acadplan_help.png
  docs/images/UserGuide/acadplan_search_full.png
  docs/images/UserGuide/acadplan_search_part.png
  docs/images/UserGuide/acadplan_viewfull.png
  docs/images/UserGuide/acadplan_viewsem.png
  docs/images/UserGuide/add_module.png
  docs/images/UserGuide/capcalc_current.png
  docs/images/UserGuide/capcalc_features.png
  docs/images/UserGuide/capcalc_set_su_module.png
  docs/images/UserGuide/capcalc_set_su_modules_output.png
  docs/images/UserGuide/capcalc_set_su_semester.png
  docs/images/UserGuide/capcalc_set_su_semester_output.png
  docs/images/UserGuide/capcalc_set_target.png
  docs/images/UserGuide/edit_module.png
  docs/images/UserGuide/edit_module_grade.png
  docs/images/UserGuide/edit_module_semester.png
  docs/images/UserGuide/exit_PlanNUS.png
  docs/images/UserGuide/exit_acadplan.png
  docs/images/UserGuide/exit_capcalc.png
  docs/images/UserGuide/file_is_empty.png
  docs/images/UserGuide/file_not_found.png
  docs/images/UserGuide/module_loaded.png
  docs/images/UserGuide/remove_module.png
Labels: feature.All, type.Documentation

#163 Bug fix and adjustment on user interaction for set su
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
  src/main/java/seedu/duke/apps/capcalculator/SetSuParser.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuByModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commands/SetSuBySemesterCommand.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetSuUtils.java
  src/main/java/seedu/duke/apps/capcalculator/commons/SetTargetUtils.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/CapCalculatorException.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/InvalidCapException.java
  src/main/java/seedu/duke/apps/capcalculator/exceptions/InvalidCreditException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/apps/capcalculator/SetSuParserTest.java
  src/test/java/seedu/duke/apps/capcalculator/commons/CalculatorUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetSuUtilsTest.java
  src/test/java/seedu/duke/apps/capcalculator/commons/SetTargetUtilsTest.java
Labels: type.BugFix

#166 Update links in UG and DG
  README.md
  docs/Configuration.md
  docs/DeveloperGuide.md
  docs/DocumentationGuide.md
  docs/LoggingGuide.md
  docs/README.md
  docs/TestingGuide.md
  docs/UserGuide.md
Labels: type.Documentation

#167 Updated DevOps Documentation, Added CodeCov badge, Fix Interaction Diagram
  .travis.yml
  README.md
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/DocumentationGuide.md
  docs/LoggingGuide.md
  docs/README.md
  docs/TestingGuide.md
  docs/UserGuide.md
  docs/base/Packages Interaction.drawio
  docs/images/DeveloperGuide/PackagesInteraction.png
  docs/images/DeveloperGuide/Packages_Interaction.png
  docs/team/Khenus.md
Labels: type.Documentation, type.Enhancement

#169 Add PlanNUS logo to all guides
  README.md
  docs/ConfigurationGuide.md
  docs/DevOpsGuide.md
  docs/DeveloperGuide.md
  docs/DocumentationGuide.md
  docs/LoggingGuide.md
  docs/README.md
  docs/TestingGuide.md
  docs/UserGuide.md
  docs/images/PlanNUSLogo.png
Labels: type.Documentation

#170 Fix broken image link in README.md
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.BugFix, type.Documentation

#172 Add details section in DG
  docs/DeveloperGuide.md
Labels: type.Documentation

#177 Fix glossary hyperlinks
  docs/DeveloperGuide.md
Labels: type.Documentation

#175 Add architecture diagram for Ui component in details
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Ui_architecture.png
Labels: type.Documentation

#178 Add architecture diagrams for storage and details
  docs/DeveloperGuide.md
  docs/images/DeveloperGuide/Details_architecture.png
  docs/images/DeveloperGuide/Storage_architecture.png
Labels: type.Documentation

#179 Edit add module command diagrams and DG
  docs/DeveloperGuide.md
  docs/base/Ui architecture.drawio
  docs/base/addModuleCommand_activity.drawio
  docs/base/addModuleCommand_finalState.drawio
  docs/base/addModuleCommand_initialState.drawio
  docs/base/addModuleCommand_sequence.drawio
  docs/base/addModuleCommand_state2.drawio
  docs/base/addModuleCommand_state6.drawio
  docs/images/DeveloperGuide/addModuleCommand_finalState.png
  docs/images/DeveloperGuide/addModuleCommand_initialState.png
  docs/images/DeveloperGuide/addModuleCommand_state2.png
  docs/images/DeveloperGuide/addModuleCommand_state6.png
Labels: type.Documentation

#180 Updated global image
  docs/DeveloperGuide.md
  docs/base/Global Diagram.drawio
  docs/base/Project Structure.drawio
  docs/images/DeveloperGuide/Global_Diagram.png
  docs/images/DeveloperGuide/ProjectStructure.png
  docs/images/DeveloperGuide/Project_structure.png
Labels: type.Documentation

#219 Add PPP for Jerrold and minor bug fixes
  docs/README.md
  docs/UserGuide.md
  docs/team/Lam.md
Labels: type.BugFix, type.Documentation

#220 Resolve Bugs
  .gitignore
  src/main/java/seedu/duke/apps/academicplanner/AcademicPlannerParser.java
  src/main/java/seedu/duke/apps/academicplanner/commands/AddModuleCommand.java
  src/main/java/seedu/duke/apps/capcalculator/CapCalculatorParser.java
Labels: feature.AcademicPlanner, type.BugFix

#221 Amend error messages for editModuleCommand
  src/main/java/seedu/duke/apps/academicplanner/commands/EditModuleCommand.java
Labels: type.BugFix
